apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
  labels:
    app: multi-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
          name: http-tool
        env:
        - name: HTTP_PORT
          value: "8080"
